# Generated by Django 4.1.5 on 2023-02-07 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_driver', models.BooleanField(default=False)),
                ('is_login', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('plate_number', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('spec_info', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vber.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_share', models.BooleanField(default=False)),
                ('dest_addr', models.CharField(max_length=50)),
                ('required_time', models.DateTimeField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('number_in_party', models.JSONField()),
                ('spec_info', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_as_owner', to='vber.user')),
                ('sharer', models.ManyToManyField(blank=True, related_name='ride_as_sharer', to='vber.user')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vber.vehicle')),
            ],
        ),
    ]
