# Generated by Django 4.1.5 on 2023-02-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vber', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
