# Generated by Django 4.1.5 on 2023-02-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vber', '0008_ride_can_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='is_login',
        ),
    ]
