# Generated by Django 4.1.5 on 2023-02-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vber', '0010_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='number_in_party',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
