# Generated by Django 4.1.5 on 2023-02-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vber', '0011_ride_number_in_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, null=True, related_name='ride_as_sharer', to='vber.user'),
        ),
    ]
